[package]
name = "biodivine-lib-bdd"
version = "0.1.0"
authors = ["Samuel Pastva <daemontus@gmail.com>"]
edition = "2018"
description = "A simple thread-safe implementation of basic binary decision diagrams."
homepage = "https://github.com/sybila/biodivine-lib-bdd"
repository = "https://github.com/sybila/biodivine-lib-bdd"
readme = "README.md"
keywords = ["bdd", "boolean-expression", "symbolic"]
categories = ["data-structures", "mathematics", "science"]
license = "MIT"

[badges]
travis-ci = { repository = "sybila/biodivine-lib-bdd" }
codecov = { repository = "sybila/biodivine-lib-bdd" }
maintenance = { status = "actively-developed" }

[profile.release]
# This is important for profiling - otherwise we would get unreadable traces.
debug = true
# This gives a marginally better runtime, but a much much longer compile times, so disabled by default.
# lto = true
# codegen-units = 1

[dependencies]
fxhash = "0.2.1"
bex = "0.1.3"

[dev-dependencies]
rand = "0.7"

[features]
# Use this config flag to enable checks or validation that should not be necessary
# (for example, the check can fail only if function contract is violated).
# In production/benchmark releases, this feature should be disabled to enable best
# performance. Avoid introducing dead code when shields_up is on, to avoid
# dead code coverage issues.
shields_up = []

# Use this to indicate that the benchmark can take a significant amount of time and thus can be filtered
# out during quick iterative testing.
large_benchmarks = []

# Enables Bex benchmarks
bench_bex = []

# Enable rich docs for some online docs autogen services.
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./res/docs-head.html"]